apiVersion: v1
kind: ReplicationController
metadata:
  name: ReplicationController Template
  namespace: main
  labels:
        environment: production
spec:
  template:
    spec:
        automountServiceAccountToken: true
